spring.application.name=BootJpa_P11-h2InMemoryDb

#H2 DB datasource configuration
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=root
spring.datasource.password=root

#H2 JPA Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Embedded Db port number
server.port=4041

#Enable H2 db console
spring.h2.console.enabled=true